// POKE API ACTIONS
export const GET_FIRST_RENDER = "GET_FIRST_RENDER"
export const GET_POKEMON_NAMES = "GET_POKEMON_NAMES"
export const GET_POKEMON_DETAILS = "GET_POKEMON_DETAILS"
export const API_ERROR = "API_ERROR"

// POKE TEAM ACTIONS
export const ADD_FAVORITE_POKEMON = "ADD_FAVORITE_POKEMON"
export const REMOVE_FAVORITE_POKEMON = "REMOVE_FAVORITE_POKEMON"
export const ADD_TO_TEAM = "ADD_TO_TEAM"
export const REMOVE_FROM_TEAM = "REMOVE_FROM_TEAM"
